spring.application.name=yard
spring.profiles.active=local
gemini.api.key=

spring.datasource.url=jdbc:postgresql://localhost:5432/yard
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
